### ISSUE TITLE
Code

### ISSUE THREAD

**Issue by Zhangyong-Tang** [Zongwei97/UnTrack#1]
Hi, thanks for your good work for the  community.

My questiona are as follows:
1. the resutls published in your paper seems incorrect. the SR of ViPT on Lasher is 0.525 (in the official paper) not 0.632 in your current version.
2. when will the code being published

**Comment by Zongwei97** [comment]
Hi,

Thanks for your interest in our work.

1. For the Lasher metrics, we followed this [toolkit](https://github.com/jiawen-zhu/ViPT/issues/10) which is provided in ViPT issues. We tested with Matlab 2023b on different computers but consistently obtained higher SR. So we reported what we had. For a fair comparison, we evaluated all the SOTA methods with the same toolkit. As you may see, for ProTrack for ex, we also obtained a higher SR compared to the one reported in ViPT.

2. We may have some following work to do in the upcoming months. From this regard, we should be able to release the code around next spring if everything goes well. Stay tuned.

**Comment by laisimiao** [comment]
@Zongwei97 
Do you get the same performance using our provided toolkit and our raw results? It can verify the impact of Matlab version.

**Comment by laisimiao** [comment]
@Zongwei97 From many paper about RGB-T trackers I read, it is so difficult now for a tracker to achieve 0.6 SR on LasHeR. So, I have a big doubt that whether matlab version influence the results so much? (We use a older one: matlab2017)

**Comment by Zhangyong-Tang** [comment]
I donot think this is something about the matlab version. Actually I think the author forgot to switch the flag, which is highlighted in the toolkit, line 70 in the main file.

**Comment by Zongwei97** [comment]
Hi,

I think you are right. We forgot to switch the flag. The results we reported were based on the flag "threshold", rather than the "AUC". Sincere apologies for the mistake. We will recompute everything and update the Arxiv version. 

Thanks a lot for the concerns.
Best

**Comment by Zongwei97** [comment]
Here is the result after switching the flag:
![SR2](https://github.com/Zongwei97/UnTrack/assets/56023848/909dfa43-14b6-4981-9bd6-a41173a74bcf)
Otherwise, the thermal finetuned performances are as follows:
ProTrack - ViPT - Ours
0.420 - 0.525 - 0.530 

We will update it in the revised version.
Thanks again for pointing out the issues.

**Comment by Zhangyong-Tang** [comment]
Thanks for letting me know, and thanks again for your good work!

**Comment by Zongwei97** [comment]
Sincere apologies and thanks again to all for pointing out the issue!

-on behalf of all authors

**Comment by XiantaoHu** [comment]
Hi 
Could you please provide a success rate  for finetuned thermal-specific parameters?

**Comment by Factral** [comment]
any updates on the code?

**Comment by Zongwei97** [comment]
Hi,

Thanks for your interest in our work. 

We are using one part of the code for another project, which was not initially foreseen... 

We will release the code ASAP.
