### ISSUE TITLE
How to evaluate of ViPT under `Single Set of Parameters` setting?

### ISSUE THREAD

**Issue by laisimiao** [Zongwei97/UnTrack#2]
What are your specific implementations?

**Comment by Zongwei97** [comment]
Hi, 

To train the uni setting, we first merged RGB-D/T/E dataloaders together, the same as the RGB tracking setting by merging GOT10K, LaSOT etc. 

To train the model, we follow the original ViPT training setting without changing anything.

For inference, we test on all datasets with the same parameter set.
