### ISSUE TITLE
a little bug in vit_ce_prompt.py

### ISSUE THREAD

**Issue by XiaokunFeng** [Zongwei97/UnTrack#6]
Thank you for your great work. 

I notice a small bug while running the program. In `lib/models/untrack/vit_ce_prompt.py` at line 523, 

![image](https://github.com/user-attachments/assets/973d6106-bff0-45bd-865e-4a1fb75ce11f)

the correct code should be:

```python
x_rgb_4edge, max_rgb_x_edge = gradient(x_dte)
```

**Comment by Zongwei97** [comment]
Thanks for carefully checking the code. Indeed there is a typo ...
