### ISSUE TITLE
Assistance Needed for Testing RGBD

### ISSUE THREAD

**Issue by XiaokunFeng** [Zongwei97/UnTrack#7]
Thanks for your great work! 

While testing with the RGBD dataset, I installed the necessary `vot-toolkit` tools (the default installation includes the latest versions of the `vot-toolkit` and `vot-trax` libraries). However, when I used the `vot` command to run evaluations, I noticed some discrepancies between the interfaces provided by the installed libraries and those used in the program.

For example, the method for defining a `trax` object in the program (in `lib/test/vot/vot.py` at line 43) is:

```python
self._trax = trax.Server([region_format], [trax.Image.PATH], channels, customMetadata=dict(vot="python"))
```

However, the `__init__` interface of the `Server` class in the `trax` library is:

```python
class Server(object):
    """ TraX server."""
    def __init__(self, region_formats, image_formats, image_channels=["color"], tracker_name="", tracker_description="", tracker_family="", metadata=None, log=False, multiobject=False):
```

As you can see, there is no `customMetadata` argument in the `trax.Server` initialization.

I suspect this issue might be related to a version mismatch between the `vot-toolkit` and `vot-trax` libraries. Could you kindly share the versions of these two libraries in your conda environment? The default versions installed on my end are ：
![image](https://github.com/user-attachments/assets/52fc5857-308c-49be-bf1b-45da04944f05)

Thank you very much for your assistance!

**Comment by Zongwei97** [comment]
I use the following versions

vot-toolkit               0.5.3                    pypi_0    pypi
vot-trax                  3.0.2                    pypi_0    pypi
